### ISSUE TITLE
Generic task notifications about configured scripts

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/boss#91]
## Generic Notifications for scripts
* Support generic notifications for scripts.
* Ability to get notified for the when certain task or script is run.
* Need a new configuration block such as `notified_scripts` (or a better name)
* For instance:
Configuration could be as simple as:
```yml
project_name: my-app
scripts: 
  db_migrate: 'yarn db:migrate'
  db_rollback: 'yarn db:rollback'
  reload: 'pm2 reload'

notifications:
  slack:
    ...
  hipchat:
    ...

notified_hooks: 
  scripts: ['reload', 'db_migrate', 'db_rollback']
```
Now, if the user executes the command:
```
$ fab staging run:db_migration
```
In hipchat or slack, the notifications would look like:
```
- kabir is running db_migrate for my-app on staging server.
- kabir finished running db_migrate for my-app on staging server.
```
